version: "3.5"
services:
    mysql:
        container_name: axul_user
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8082:8082"
        environment:
            - APP_PORT=8082
            - TOKEN=
            - DATABASE_HOST=
            - DATABASE_PORT=3306
            - DATABASE_NAME=axul_user
            - DATABASE_USER=root
            - DATABASE_PASSWORD=
            - DATABASE_DEBUG=true
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "10m"
        networks:
            - appnet
networks:
    appnet:
        driver: "bridge"
            