FROM golang:1.15

RUN mkdir -p $GOPATH/src/github.com/ncostamagna/axul_user
WORKDIR $GOPATH/src/github.com/ncostamagna/axul_user
COPY . .
RUN ls

ARG DATABASE_HOST
ARG DATABASE_USER
ARG DATABASE_PASSWORD 
ARG DATABASE_NAME
ARG DATABASE_PORT
ARG DATABASE_DEBUG
ARG DATABASE_MIGRATE


ENV DATABASE_HOST $DATABASE_HOST
ENV DATABASE_USER $DATABASE_USER
ENV DATABASE_PASSWORD $DATABASE_PASSWORD
ENV DATABASE_NAME $DATABASE_NAME
ENV DATABASE_PORT $DATABASE_PORT
ENV DATABASE_DEBUG $DATABASE_DEBUG
ENV DATABASE_MIGRATE $DATABASE_MIGRATE

RUN go get -d -v ./... 
RUN go install -v ./...
EXPOSE 8082
EXPOSE 50055

CMD ["axul_user"]