version: "3.5"
services:
  axul_database:
    platform: linux/amd64
    container_name: axul_database
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: axul_user
    ports:
      - "3323:3306"
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql